### ISSUE TITLE
Inconsistent name of login file

### ISSUE THREAD

**Issue by bjiang97** [Stephen-X123/deliveryProject#4]
In `App.js` file, `import Login from './components/Login.js'`, but the name of that file is `login.js`. You may need to change the file name.

**Comment by Stephen-X123** [comment]
Ah, good catch. I think I tried to make them all upper case but did not change them in the components folder. Or I forgot to submit the commit with the name changes.

**Comment by Stephen-X123** [comment]
Well. This is weird. The files are name correctly on my local machine. I commit and push. The push is successful. Hours ago I demonstrated that App.js runs successful. Any name difference should have triggered an error there. I am really sorry about any inconvenience this may cause if you cannot run the code for this reason.

**Comment by bjiang97** [comment]
I don't know if you just change the file name to uppercase `Login.js` just now but the problem still exists, it's still `import...from Login.js` in `App.js`, and that file is called `login.js`. The git will not detect the changing between lowercase to uppercase unless you change the default setting by using `git config core.ignorecase false`. I just try this way and it works. Ref link: [](https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git)

**Comment by Stephen-X123** [comment]
I think I got the upper case files in there, but the lower case files are still there as well.
